name: "Build"
on:
  pull_request:
  push:
jobs:
  fernglas:
    strategy:
      matrix:
        packageset: [
          "pkgs",
          "pkgsStatic",
          "pkgsCross.musl64",
          "pkgsCross.aarch64-multiplatform",
          "pkgsCross.aarch64-multiplatform.pkgsStatic",
          "pkgsCross.aarch64-multiplatform-musl"
        ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: cachix/install-nix-action@v23
    - uses: cachix/cachix-action@v12
      with:
        name: wobcom-public
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: 'nix build .#${{ matrix.packageset }}.fernglas -vL'
    - uses: actions/upload-artifact@v3
      with:
        name: '${{ matrix.packageset }}.fernglas'
        path: result/bin/fernglas
  fernglas-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: cachix/install-nix-action@v23
    - uses: cachix/cachix-action@v12
      with:
        name: wobcom-public
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#fernglas-frontend -vL
    # https://github.com/actions/upload-artifact/issues/92
    - run: cp -r result/ result-frontend
    - uses: actions/upload-artifact@v3
      with:
        name: fernglas-frontend
        path: result-frontend/*
