name: "Docker"
on:
  push:
    branches:
      - main
jobs:
  fernglas:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: cachix/install-nix-action@v23
    - uses: cachix/cachix-action@v12
      with:
        name: wobcom-public
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#fernglas-docker -vL
    - run: 'nix run .#skopeo -- login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io'
    - run: 'nix run .#skopeo -- copy docker-archive://$(readlink ./result) docker://ghcr.io/wobcom/fernglas:latest'
  fernglas-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: cachix/install-nix-action@v23
    - uses: cachix/cachix-action@v12
      with:
        name: wobcom-public
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#fernglas-frontend-docker -vL
    - run: 'nix run .#skopeo -- login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io'
    - run: 'nix run .#skopeo -- copy docker-archive://$(readlink ./result) docker://ghcr.io/wobcom/fernglas-frontend:latest'
